import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Sidebar from "./components/elements/Sidebar/Sidebar";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [game, setGame] = useState({});
  useEffect(() => {
    setGame({
      name: "The Game",
      description: "A game about a game",
      version: "0.0.1",
    });
  }, []);
  return (
    <>
      <Head>
        <title>{game.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-900">
        <Sidebar game={game} />
      </main>
    </>
  );
};

export default Home;
